---
- hosts: all
  become: true
  tasks:
  - name: ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - vim
        - wget
        - git
        - docker

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: start and enable docker
    systemd:
      state: started
      enabled: yes
      name: docker



