---
- hosts: all
  become: true
  tasks:
  - name: ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - vim
        - wget
        - git
        - docker
        - epel-release

  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive

  - name: start and enable docker
    systemd:
      state: started
      enabled: yes
      name: docker

  - name: install python pip
    yum:
      name: python-pip
      state: latest

  - name: install docker via pip
    pip:
      name: docker

  - name: Container present
    docker_container:
      name: mycontainer
      state: started
      image: httpd
      published_ports: 80:80


